package com.aigora.tutororchestrator.application.error;
public enum SessionErrorCode { VALIDATION_FAILURE, SESSION_NOT_FOUND, SESSION_ALREADY_EXISTS, INVALID_TRANSITION, VERSION_CONFLICT, STALE_ASSESSMENT, ASSESSMENT_UNAVAILABLE, ORCHESTRATION_UNAVAILABLE, NO_ELIGIBLE_CANDIDATE, EVENT_PUBLICATION_FAILURE, TRACE_RECORDING_FAILURE }
