package com.aigora.tutororchestrator.application.usecase;
import com.aigora.tutororchestrator.application.contracts.command.*;import com.aigora.tutororchestrator.application.context.*;import com.aigora.tutororchestrator.application.ports.*;import com.aigora.tutororchestrator.application.usecase.*;import com.aigora.tutororchestrator.domain.model.*;import com.aigora.tutororchestrator.domain.valueobjects.*;import com.aigora.tutororchestrator.infrastructure.*;import org.junit.jupiter.api.Test;import java.time.*;import static org.junit.jupiter.api.Assertions.*;
class LearningSessionEndToEndTest {
 @Test void shouldStartCompleteAssessAndApplyNextNode(){var repo=new InMemoryLearningSessionRepository();var events=new InMemorySessionEventPublisher();var traces=new InMemorySessionDecisionTraceSink();var telemetry=new InMemoryLifecycleTelemetrySink();Clock clock=Clock.fixed(Instant.parse("2026-08-20T12:00:00Z"),ZoneOffset.UTC);SessionAssessmentClient assessment=id->new SessionAssessmentSnapshot(id,new ExerciseAttemptId("a1"),new NodeId("n1"),true,false);TutorOrchestratorClient tutor=req->new SessionOrchestrationDecision(new DecisionId("d1"),req.sessionId(),req.sessionVersion(),req.assessmentResultId(),OrchestrationOutcome.NEXT_NODE,new NodeId("n2"));var start=new StartLearningSessionUseCase(repo,events,telemetry,clock);var complete=new CompleteExerciseUseCase(repo,events,telemetry,clock);var process=new ProcessLearningProgressUseCase(repo,events,assessment,tutor,traces,telemetry,clock);
 var sr=start.execute(new StartLearningSessionCommand(new LearningSessionId("s1"),new StudentId("u1"),new NodeId("n1"),new ExerciseId("e1"),new CommandId("start"),new CorrelationId("c"),new CausationId("root")));assertTrue(sr.isSuccess());
 var cr=complete.execute(new CompleteExerciseCommand(new LearningSessionId("s1"),sr.value().version(),new ExerciseAttemptId("a1"),new ExerciseId("e1"),new CommandId("complete"),new CorrelationId("c"),new CausationId("start")));assertTrue(cr.isSuccess());
 var pr=process.execute(new ProcessLearningProgressCommand(new LearningSessionId("s1"),cr.value().version(),new AssessmentResultId("r1"),new OrchestrationRequestId("req1"),new GraphVersion("g1"),new StudentModelVersion("sm1"),new PolicySetVersion("p1"),new CommandId("progress"),new CorrelationId("c"),new CausationId("complete")));assertTrue(pr.isSuccess());assertEquals(LearningSessionStatus.ACTIVE,pr.value().status());assertEquals(new NodeId("n2"),pr.value().currentNodeId());assertEquals(1,traces.recordedDecisions().size());assertEquals(4,events.publishedEvents().size());
 }
 @Test void shouldCompleteSessionOnTerminalDecision(){var repo=new InMemoryLearningSessionRepository();var events=new InMemorySessionEventPublisher();var traces=new InMemorySessionDecisionTraceSink();var telemetry=new InMemoryLifecycleTelemetrySink();Clock clock=Clock.fixed(Instant.EPOCH,ZoneOffset.UTC);SessionAssessmentClient assessment=id->new SessionAssessmentSnapshot(id,new ExerciseAttemptId("a1"),new NodeId("n1"),true,false);TutorOrchestratorClient tutor=req->new SessionOrchestrationDecision(new DecisionId("d1"),req.sessionId(),req.sessionVersion(),req.assessmentResultId(),OrchestrationOutcome.COMPLETED,null);var start=new StartLearningSessionUseCase(repo,events,telemetry,clock);var complete=new CompleteExerciseUseCase(repo,events,telemetry,clock);var process=new ProcessLearningProgressUseCase(repo,events,assessment,tutor,traces,telemetry,clock);var sr=start.execute(new StartLearningSessionCommand(new LearningSessionId("s1"),new StudentId("u1"),new NodeId("n1"),new ExerciseId("e1"),new CommandId("start"),new CorrelationId("c"),new CausationId("root")));var cr=complete.execute(new CompleteExerciseCommand(new LearningSessionId("s1"),sr.value().version(),new ExerciseAttemptId("a1"),new ExerciseId("e1"),new CommandId("complete"),new CorrelationId("c"),new CausationId("start")));var pr=process.execute(new ProcessLearningProgressCommand(new LearningSessionId("s1"),cr.value().version(),new AssessmentResultId("r1"),new OrchestrationRequestId("req1"),new GraphVersion("g1"),new StudentModelVersion("sm1"),new PolicySetVersion("p1"),new CommandId("progress"),new CorrelationId("c"),new CausationId("complete")));assertTrue(pr.isSuccess());assertEquals(LearningSessionStatus.COMPLETED,pr.value().status());}
}
