package com.aigora.tutororchestrator.application.usecase;
import com.aigora.tutororchestrator.application.contracts.command.*;import com.aigora.tutororchestrator.application.error.*;import com.aigora.tutororchestrator.application.context.*;import com.aigora.tutororchestrator.application.ports.*;import com.aigora.tutororchestrator.application.contracts.result.*;import com.aigora.tutororchestrator.domain.model.*;import com.aigora.tutororchestrator.domain.policy.*;import com.aigora.tutororchestrator.domain.valueobjects.*;import java.time.*;
public final class ProcessLearningProgressUseCase {
 private final LearningSessionRepository repo; private final SessionEventPublisher publisher; private final SessionAssessmentClient assessmentClient; private final TutorOrchestratorClient orchestrator; private final SessionDecisionTraceSink traceSink; private final LifecycleTelemetrySink telemetry; private final Clock clock; private final SessionContinuationPolicy continuationPolicy=new SessionContinuationPolicy(); private final SessionCompletionPolicy completionPolicy=new SessionCompletionPolicy();
 public ProcessLearningProgressUseCase(LearningSessionRepository repo,SessionEventPublisher publisher,SessionAssessmentClient assessmentClient,TutorOrchestratorClient orchestrator,SessionDecisionTraceSink traceSink,LifecycleTelemetrySink telemetry,Clock clock){this.repo=repo;this.publisher=publisher;this.assessmentClient=assessmentClient;this.orchestrator=orchestrator;this.traceSink=traceSink;this.telemetry=telemetry;this.clock=clock;}
 public SessionResult<LearningSession> execute(ProcessLearningProgressCommand c){long started=System.nanoTime(); var opt=repo.findById(c.sessionId()); if(opt.isEmpty()) return UseCaseSupport.failure(SessionErrorCode.SESSION_NOT_FOUND,"Learning session not found"); var session=opt.get(); if(session.hasProcessed(c.commandId())) return new SessionSuccess<>(session.copy()); if(!session.version().equals(c.expectedVersion()) && session.status()==LearningSessionStatus.AWAITING_ASSESSMENT) return UseCaseSupport.failure(SessionErrorCode.VERSION_CONFLICT,"Session version mismatch");
   SessionAssessmentSnapshot assessment; try { assessment=assessmentClient.getAssessment(c.assessmentResultId()); } catch(RuntimeException e){return UseCaseSupport.failure(SessionErrorCode.ASSESSMENT_UNAVAILABLE,e.getMessage());}
   if(session.currentAttempt()==null || !session.currentAttempt().id().equals(assessment.attemptId()) || !session.currentNodeId().equals(assessment.nodeId())) return UseCaseSupport.failure(SessionErrorCode.STALE_ASSESSMENT,"Assessment does not match current session state");
   if(session.status()==LearningSessionStatus.AWAITING_ASSESSMENT){var before=session.version();session.acceptAssessment(assessment.attemptId(),assessment.assessmentResultId(),new CommandId(c.commandId().value()+":assessment"),c.correlationId(),c.causationId(),Instant.now(clock));var ev=session.drainEvents();try{repo.update(session,before);publisher.publish(ev);}catch(SessionVersionConflictException e){return UseCaseSupport.failure(SessionErrorCode.VERSION_CONFLICT,e.getMessage());}}
   if(session.status()!=LearningSessionStatus.PROCESSING_DECISION) return UseCaseSupport.failure(SessionErrorCode.INVALID_TRANSITION,"Session is not ready for orchestration decision");
   SessionOrchestrationDecision decision; try {decision=orchestrator.decide(new SessionOrchestrationRequest(c.orchestrationRequestId(),session.id(),session.version(),session.studentId(),session.currentNodeId(),assessment.attemptId(),assessment.assessmentResultId(),c.graphVersion(),c.studentModelVersion(),c.policySetVersion(),c.correlationId(),c.causationId()));} catch(RuntimeException e){return UseCaseSupport.failure(SessionErrorCode.ORCHESTRATION_UNAVAILABLE,e.getMessage());}
   if(!decision.sessionId().equals(session.id()) || !decision.expectedSessionVersion().equals(session.version()) || !decision.assessmentResultId().equals(assessment.assessmentResultId())) return UseCaseSupport.failure(SessionErrorCode.STALE_ASSESSMENT,"Orchestration decision is stale or mismatched");
   try { traceSink.record(decision); } catch(RuntimeException e){return UseCaseSupport.failure(SessionErrorCode.TRACE_RECORDING_FAILURE,e.getMessage());}
   if(decision.outcome()==OrchestrationOutcome.NO_CANDIDATE) return UseCaseSupport.failure(SessionErrorCode.NO_ELIGIBLE_CANDIDATE,"Tutor Orchestrator returned no eligible candidate");
   var before=session.version();var dc=new CommandId(c.commandId().value()+":decision"); if(completionPolicy.shouldComplete(decision.outcome())) session.completeSession(decision.decisionId(),SessionTerminalReason.LEARNING_GOAL_REACHED,dc,c.correlationId(),c.causationId(),Instant.now(clock)); else if(decision.outcome()==OrchestrationOutcome.CONTINUE_CURRENT_NODE) session.continueCurrentNode(decision.decisionId(),dc,c.correlationId(),c.causationId(),Instant.now(clock)); else if(continuationPolicy.shouldContinue(decision.outcome())) session.applyNextNode(decision.decisionId(),decision.nextNodeId(),dc,c.correlationId(),c.causationId(),Instant.now(clock)); else return UseCaseSupport.failure(SessionErrorCode.INVALID_TRANSITION,"Unsupported orchestration outcome");
   session.recordProcessedCommand(c.commandId()); var ev=session.drainEvents(); try{repo.update(session,before);try{publisher.publish(ev);}catch(RuntimeException e){return UseCaseSupport.failure(SessionErrorCode.EVENT_PUBLICATION_FAILURE,e.getMessage()==null?"Event publication failed":e.getMessage());}}catch(SessionVersionConflictException e){return UseCaseSupport.failure(SessionErrorCode.VERSION_CONFLICT,e.getMessage());}
   telemetry.record("process-progress",session.id(),session.version(),"success",System.nanoTime()-started); return new SessionSuccess<>(session.copy());
 }
}
